apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: chip
  namespace: argocd
spec:
  generators:
    - list:
        elements:
        - cluster: https://kubernetes.default.svc                                       
  template:
    metadata:
      name: chip
    spec:
      project: "chip"
      source:
        repoURL: 'http://chartmuseum.chartmuseum.svc.cluster.local:8080'
        chart: sample
        targetRevision: 0.1.0
        helm:
          releaseName: chip
          valuesObject:
            app:
              name: chip
              image: fidelissauro/chip:v1
              namespace: chip
              version: "v6"
              iam: ""
              capacity:
                requests: 
                  cpu: 100m
                  memory: 128Mi
                limits: 
                  cpu: 200m
                  memory: 256Mi
                autoscaling: {}
                min: 10
                max: 10
              rollout:
                strategy:
                  canary:
                    steps:
                    - setWeight: 0
                    - pause: {duration: 10s}
                    - setWeight: 10
                    - pause: {duration: 10s}
                    - setWeight: 20
                    - pause: {duration: 10s}
                    - setWeight: 40
                    - pause: {duration: 10s}
                    - setWeight: 80
                    - pause: {duration: 10s}             
                    - setWeight: 100

              port:
                name: http-web
                port: 8080
                protocol: TCP
                targetPort: 8080
              service:
                type: ClusterIP
              istio:
                gateway: 
                  selector: ingressgateway
                  # HTTP, HTTP2, GRPC, GRPC-WEB, MONGO, REDIS, MYSQL, TCP
                  protocol: HTTP 
                  port: 80
                host: chip.homelab.msfidelis.com.br
                virtualService:
                  http:
                    enabled: true
                    retries:
                      attempts: 2
                      perTryTimeout: 500ms
                      retryOn: connect-failure,refused-stream,unavailable,cancelled,503
                DestinationRule:
                  enabled: true

              prometheus:
                scrape: "true"
                port: 8080
                path: /metrics

              probes:
                livenessProbe:
                  enabled: true
                  failureThreshold: 10
                  periodSeconds: 10
                  httpGet:
                    path: /healthcheck
                    port: 8080
                startupProbe:
                  enabled: true
                  failureThreshold: 10
                  periodSeconds: 10
                  httpGet:
                    path: /healthcheck
                    port: 8080

      destination:
        server: '{{ cluster }}'
        namespace: argocd
      syncPolicy:
        automated: {}